server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_HOST:localhost}
