server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
      hostname: eureka-server-l9in.onrender.com
  client:
    register-with-eureka: false
    fetch-registry: false
